### ISSUE TITLE
一个令人哭笑不得的bug

### ISSUE THREAD

**Issue by L-jasmine** [clojure-link/link#42]
在我的使用tcp-server的场景中，我的客户端会自动快速重连服务器。然后我需要重启tcp-server时，它是先关闭worker之后再关闭boss,那么因为我的客户端快速重连就发生了worker永远关不掉。。。
建议更改tcp-server的关闭顺序。

**Comment by sunng87** [comment]
哈哈，欢迎提交 pull request

**Comment by sunng87** [comment]
Fixed in #43
